Name: SamplePythonApplicationWithTestCodeCoverage
RunMode: PARALLEL
SchemaVersion: "1.0"

# Optional - Set automatic triggers.
Triggers:
  - Type: Push
    Branches:
      - main

# Required - Define action configurations.
Actions:
  UnitTestAndCodeCoverage:
    Identifier: aws/managed-test@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      Artifacts:
        - Name: Artifact_Test
          Files:
            - "**/*"
      Reports:
        UnitTests:
          IncludePaths:
          Format: JUNITXML
          SuccessCriteria:
            PassRate: 90
        CoverageReport:
          IncludePaths:
            - code_coverage.xml
          Format: COBERTURAXML
          SuccessCriteria:
            LineCoverage: 99
            BranchCoverage: 100
    Configuration:
      Steps:
        - Run: yum update -y
        - Run: yum install -y python3
        - Run: curl https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py
        - Run: python3 get-pip.py
        - Run: pip install -r requirements.txt
        - Run: coverage run --branch --source=src/. -m pytest --ignore=tests/integration/
            --junitxml=output/tests/unit/test_report.xml; coverage xml -o
            code_coverage.xml
  IntegrationTests:
    Identifier: aws/managed-test@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      Artifacts:
        - Name: Artifact_Test_1
          Files:
            - "**/*"
    Configuration:
      Steps:
        - Run: yum update -y
        - Run: yum install -y python3
        - Run: curl https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py
        - Run: python3 get-pip.py
        - Run: pip install -r requirements.txt
        - Run: pytest --ignore=tests/unit/ --junitxml=output/tests/integ/test_report.xml
